# Generated by Django 5.0 on 2023-12-20 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dekan", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articles",
            options={"verbose_name": "Новость", "verbose_name_plural": "Новости"},
        ),
    ]
